baseurl = "/"
title = "Foobiebletch.net"
canonifyurls = true
languageCode = "en-US"
paginate = 5
theme = "etch"

[author]
  name = ""

SectionPagesMenu = "main"

# Configure syntax highlight
[markup]
  [markup.highlight]
    style = "rrt" # dark themes: monokai, api, fruity, native, rrt, swapoff

[[menu.main]]
  name = "Software"
  weight = 2
  identifier = "software"
  url = "/software"

[[menu.main]]
  name = "About"
  weight = 3
  identifier = "about"
  url = "/about"

[params.meta]
  keywords = "blog, tech"
  description = "Personal blog."

[params]
  theme_colors = "default-dark" # uses color css file under static/css/default-dark.css
